name: 'Generate release PR with release-please'

on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write
  
jobs:
  release-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Release with release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
